// Generated by gencpp from file pathfinding/Target.msg
// DO NOT EDIT!


#ifndef PATHFINDING_MESSAGE_TARGET_H
#define PATHFINDING_MESSAGE_TARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pathfinding
{
template <class ContainerAllocator>
struct Target_
{
  typedef Target_<ContainerAllocator> Type;

  Target_()
    : x(0)
    , y(0)  {
    }
  Target_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef uint8_t _x_type;
  _x_type x;

   typedef uint8_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::pathfinding::Target_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pathfinding::Target_<ContainerAllocator> const> ConstPtr;

}; // struct Target_

typedef ::pathfinding::Target_<std::allocator<void> > Target;

typedef boost::shared_ptr< ::pathfinding::Target > TargetPtr;
typedef boost::shared_ptr< ::pathfinding::Target const> TargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pathfinding::Target_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pathfinding::Target_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pathfinding::Target_<ContainerAllocator1> & lhs, const ::pathfinding::Target_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pathfinding::Target_<ContainerAllocator1> & lhs, const ::pathfinding::Target_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pathfinding

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pathfinding::Target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pathfinding::Target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pathfinding::Target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pathfinding::Target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pathfinding::Target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pathfinding::Target_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pathfinding::Target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "727012f6868afa655d78dc8b436d2c91";
  }

  static const char* value(const ::pathfinding::Target_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x727012f6868afa65ULL;
  static const uint64_t static_value2 = 0x5d78dc8b436d2c91ULL;
};

template<class ContainerAllocator>
struct DataType< ::pathfinding::Target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pathfinding/Target";
  }

  static const char* value(const ::pathfinding::Target_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pathfinding::Target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 x\n"
"uint8 y\n"
;
  }

  static const char* value(const ::pathfinding::Target_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pathfinding::Target_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Target_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pathfinding::Target_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pathfinding::Target_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATHFINDING_MESSAGE_TARGET_H
